knp_paginator:
    page_range: 5                      # nombre de pages affichées dans le navigateur de pagination
    default_options:
        page_name: page                # nom du paramètre de page dans l'URL
        sort_field_name: sort          # nom du paramètre de tri dans l'URL
        sort_direction_name: direction # nom du paramètre de direction dans l'URL
        distinct: true                 # ensure distinct results, useful when ORM queries are using GROUP BY statements
        filter_field_name: filterField # nom du paramètre de filtre dans l'URL
        filter_value_name: filterValue # nom du paramètre de valeur de filtre dans l'URL
    template:
        pagination: '@KnpPaginator/Pagination/bootstrap_v5_pagination.html.twig'     # template de pagination
        sortable: '@KnpPaginator/Pagination/sortable_link.html.twig'                # template pour les liens de tri
        filtration: '@KnpPaginator/Pagination/filtration.html.twig'                 # template pour le filtrage